// <auto-generated />
namespace ApiImoveis.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0-preview1-19506-01")]
    public sealed partial class AddNumero : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddNumero));
        
        string IMigrationMetadata.Id
        {
            get { return "201910301935297_AddNumero"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
